apiVersion: execution.securecodebox.io/v1
kind: ScanType
metadata:
  name: tlsx2
  namespace: securecodebox-system
spec:
  extractResults:
    type: tlsscan-json
    location: "/home/output.json"
  parameters:
    - name: host
      type: string
      required: true
  # Optional: You can add more parameter definitions if needed
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: tlsx2
              image: pranavbhat3/tlsx-scanner:latest
              args:
                - "-host"
                - "{{ .host }}"
                - "-json"
                - "-o"
                - "/home/output.json"
