# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "cascading.securecodebox.io/v1"
kind: CascadingRule
metadata:
  name: "zap-https"
  labels:
    securecodebox.io/invasive: non-invasive
    securecodebox.io/intensive: medium
spec:
  matches:
    anyOf:
      - category: "Open Port"
        attributes:
          service: "https*"
          state: open
  scanSpec:
    scanType: "zap-automation-framework"
    parameters:
      - "-autorun"
      - "/home/securecodebox/scb-automation/automation.yaml"
    volumeMounts:
      - name: zap-automation-framework-baseline-config  
        mountPath: /home/securecodebox/scb-automation/automation.yaml
        subPath: automation.yaml
    volumes:
      - name: zap-automation-framework-baseline-config  
        configMap:
          name: zap-automation-framework-baseline-config  
    env: 
      - name: TARGET_URL
        value: "https://{{$.hostOrIP}}:{{attributes.port}}"
