# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: git-repo-scanner
description: A Helm chart for the git-repo-scanner that integrates with the secureCodeBox.

type: application
# version - gets automatically set to the secureCodeBox release version when the helm charts gets published
version: v3.1.0-alpha1
appVersion: "1.1"
kubeVersion: ">=v1.11.0-0"
annotations:
  # supported cpu architectures for which docker images for the scanner should be build
  supported-platforms: linux/amd64

keywords:
  - git
  - repositories
  - scanner
  - secureCodeBox
home: https://www.securecodebox.io/docs/scanners/git-repo-scanner
icon: https://www.securecodebox.io/img/integrationIcons/GitRepoScanner.svg
sources:
  - https://github.com/secureCodeBox/secureCodeBox
maintainers:
  - name: iteratec GmbH
    email: secureCodeBox@iteratec.com
