apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobsf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobsf
  template:
    metadata:
      labels:
        app: mobsf
    spec:
      containers:
        - name: mobsf
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MOBSF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mobsf-api-key
                  key: api-key
