apiVersion: v1
kind: Service
metadata:
  name: mobsf
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: mobsf
