apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobsf-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobsf-webapp
  template:
    metadata:
      labels:
        app: mobsf-webapp
    spec:
      serviceAccountName: mobsf-webapp
      containers:
      - name: mobsf-webapp
        image: acc0lade/mobsf-webapp:v6  # or <your-registry>/mobsf-webapp:latest
        ports:
        - containerPort: 8088
        env:
        - name: MINIO_ENDPOINT
          value: "http://securecodebox-operator-minio.securecodebox-system.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          value: "admin"
        - name: MINIO_SECRET_KEY
          value: "password"
        - name: MINIO_BUCKET
          value: "securecodebox"
        - name: K8S_NAMESPACE
          value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: mobsf-webapp
spec:
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    app: mobsf-webapp